name: Create issue on commit

on: [ push ]

jobs:
  test:   
    runs-on: ubuntu-latest
    steps:
      - id: xxx
        shell: bash
        run: |

          APP="-H 'Accept: application/vnd.github+json'"
          AUT="Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'"
          VER="-H 'X-GitHub-Api-Version: 2022-11-28'"
          URL="https://api.github.com/repos/makramjandar/temp-repo/environments"

          echo "curl -L $APP $AUT $VER $URL"

          CMD() { curl -L "$APP" "$AUT" "$VER" "$URL" ;}
          CMD

          #CMD=('curl' '-L' "$APP" "$AUT" "$VER" "$URL")
          #"${CMD[@]}"
      
      - id: list-envs
        shell: bash
        run: |
          API="$(
            curl -L \
            -H 'Accept: application/vnd.github+json' \
            -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            -H 'X-GitHub-Api-Version: 2022-11-28' \
            https://api.github.com/repos/makramjandar/temp-repo/environments
          )"

          ENVS=$(echo "$API" | jq '.environments[].name')
          
          echo "envs=$(echo $ENVS)" >> $GITHUB_OUTPUT

      - run: echo ${{ steps.list-envs.outputs.envs }}
        shell: bash
