# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    
    steps:

      - uses: actions/checkout@v3
      - uses: makramjandar/action-github-branch-name@v1

      - name: test-action
        run: echo "${{ steps.extract_branch.outputs.branch }}"
        
      - name: test-echo
        run: echo "+++++++++++++++++++++++++++++++++++++++++++++"

      - name: x branch name
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: test_branch

      - name: test-action
        run: echo "${{ steps.test_branch.outputs.branch-name }}"
