# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    
    steps:

      - uses: actions/checkout@v3
      - uses: makramjandar/action-github-branch-name@main

      - name: test-action
        run: echo "${{ steps.extract_branch.outputs.branch }}"
        
      - name: test-action
        run: echo "+++++++++++++++++++++++++++++++++++++++++++++"
        
